### ISSUE TITLE
Integrate capsolver

### ISSUE THREAD

**Issue by Xeeeno** [justhyped/gocaptcha#4]
Hey, it's possible that you integrate [capsolver.com](https://www.capsolver.com/), they have the cheapest and fastest captcha solution of the whole market.
They can solve hcaptcha, recaptcha, amazon waf captcha, turnstile, kasada, akamai, funcaptcha, datadome captcha, geetest etc...
Also you can check their documentation here: https://docs.capsolver.com/

**Comment by justhyped** [comment]
Hi,

I've looked through their docs. Seems like they have an identical API to that of AntiCaptcha so you will be able to use their captcha api without a problem by setting `CustomServiceUrl `. I'm not looking to add anti-bots to this project.

**Comment by Xeeeno** [comment]
Hey, they only support 2captcha api, but could be great that you implement as another solution so i dont need to change host

**Comment by justhyped** [comment]
It's the exact reason why `CustomServiceUrl` was added. It's used to support a lot of different providers that use the same API endpoints and properties without adding unnecessary amounts of code to the project for individual providers that do the exact same thing.
