### ISSUE TITLE
Integrate AntiGateTask for Anti-Captcha

### ISSUE THREAD

**Issue by n0v3xx** [justhyped/gocaptcha#5]
Hi,
could you please add another method to make a request for the AntiGateTask?

-> https://anti-captcha.com/de/apidoc/task-types/AntiGateTask

Best regards

**Comment by justhyped** [comment]
I've looked at the documentation and I think this type of task is out of scope for this repository. It could work by adding a method to the interface that takes in the `variables` as a map but the returned solution would also have to be some sort of map for this type of 'captcha'.

If you intend to use AntiGate I suggest you write your own function for it that can then fit to your exact requirements.

**Comment by hacknapier** [comment]
https://github.com/flyCaptcha/flyCaptcha
